---
title: "Quasirandomisation"
author: "Franz Prücklmair"
date: "14 3 2022"
output: 
  html_document: 
    keep_md: yes
editor_options: 
  chunk_output_type: inline
---
## Packages 
```{r setup, include=FALSE}

# 
rm(list=ls())
# install.packages("knitr")
# install.packages("dplyr")
# install.packages("tidyverse")
# install.packages("icarus")
# install.packages("stargazer")
# install.packages("Metrics")
# install.packages("gridExtra")
# install.packages("survey")
# install.packages("psych")
# install.packages("lmtest")
library(tidyverse)
library(foreign)
library(dplyr)
library(survey)
library(icarus)
library(stargazer)
library(Metrics)
library(gridExtra)
# library(psych)
library(lmtest)
knitr::opts_chunk$set(echo = T)
```

## Datensatz
```{r}

ESS9DE <- read.spss(file = "Z:/Civey/R/Daten/ESS9DE.sav",
                    to.data.frame = T,
                    use.value.labels = F)

# # ESS Parteiverteilung
# table(ESS9DE$vote,exclude=NULL)
# sum(table(ESS9DE$prtvede1))
# sum(table(ESS9DE$prtvede2,exclude=NULL))
# 
# # ESS Parteinäheverteilung
# table(ESS9DE$clsprty,exclude=NULL)
# sum(table(ESS9DE$prtclede))
# sum(table(ESS9DE$prtvede2,exclude=NULL))

```
## Funktionen
```{r}
design.table <- function(x,y,z){
d <- svydesign(~1,weights = y,data = x)
e <-round(prop.table(svytable(z,design =  d)),3)*100
return(e)
}

sampling_wr <- function(x,c,e){
 h <-  ifelse(e ==T,T,F)
  z <- sample(1:nrow(x), c, replace = h)
  y <- x[z,]
}

qrm <- function(ref,volunt) {
 # nonprob bekommt Z=1 und reference survey Z=0
ref$Z <- rep(0, length(ref[,1]))
volunt$Z <-  rep(1, length(volunt[,1]))
  
#concatenate reference sample and nonprob sample
joint_ref_volunt <- rbind(ref,volunt)
  
# Invertierung Z Berechnet P(Z=0)
joint_ref_volunt$Zinv  <- ifelse(joint_ref_volunt$Z == 0,1,0)

model_volunt= glm(as.formula(paste("Zinv ~ ", paste(xnam))),data=joint_ref_volunt,
                   family=binomial())

sample_volunt  <- subset(joint_ref_volunt, Z==1)

#Berechnung von P(Z=0)
sample_volunt$P_Z <- predict(model_volunt,sample_volunt ,type = 'response')
#Berechnung von P(Z=0)/(1-P(Z=0))
sample_volunt$corr_final <- sample_volunt$P_Z/(1-sample_volunt$P_Z)
# sample_volunt$corr_final <- sample_volunt$corr_final*2500/sum((sample_volunt$corr_final))



}


rakemarg <- function(x,y){
  margins_2 <- matrix(nrow = length(variable.names(xVar)),ncol = 4)
  for (i in 1:length(variable.names(y))) {
 n <- variable.names(x[variable.names(y)])[i]
  c <- (dim( table(x[variable.names(y)][i])))
  v1 <- table(x[variable.names(y[i])])[1]
  v2 <- table(x[variable.names(y[i])])[2]
 vec <- c(n,c,v1,v2)
 margins_2[i,] <-   vec 
  } 
  return(margins_2)
}


abs.bias <- function(x,y){
 z <-  (x-y)
 return(z)
}
  rel.bias <- function(x,y){
    z <-  (x-y)
    z*100/y
  }
  
se  <- function(x,y){
    z <-  (x-y)^2
  }
  
  
plotter <- function(df1,var1,var2,df2,var3,var4,yname){
 a <-  ggplot() +               
  geom_boxplot(data = df1, aes(var1,var2,fill = Selektion), 
             show.legend = FALSE)+ scale_fill_brewer(palette="Blues")+
  stat_summary(data = df1, aes(var1,var2),fun = "mean",color = "black", shape = 15)+
  geom_point(data = df2, aes(var3,var4),color= "red", size=2.5)+
  geom_hline(yintercept = 0,color = "red",size=1.3)+ 
  xlab("")+ 
  ylab(yname)
}  
```


## Recodierung

```{r}

ESS9DE$internet<- ifelse(ESS9DE$netustm >= 180,1,0)
ESS9DE <- ESS9DE %>% mutate(internet= netustm >= 180,
                            blogger = pstplonl == 1,
                            interpol = netustm >= 180 & ESS9DE$polintr <= 2)


# Verteilungen ohne PolitikInteresse/Aktivität ----------------------------
# echtes Wahlergebniss 2017 mit nichtwählern
summ <- sum(c( 33, 20.5, 9.2, 8.9, 10.7, 12.6, 5))
wahlnw <- c(round((c( 33, 20.5, 9.2, 8.9, 10.7, 12.6, 5)*76.2/summ),1),23.8)
wahl <- c( 33, 20.5, 9.2, 8.9, 10.7, 12.6, 5)
# rekodierung der Variablen ------------------------------------------------------------------
ESS9DE$edubde1[which(ESS9DE$edubde1==0|ESS9DE$edubde1==1|ESS9DE$edubde1==5555)] <- NA
ESS9DE <- ESS9DE %>% mutate(male = gndr == 1,
                            age_le_20 = agea <=  20,
                            age_20_40 = agea > 20 & agea <= 40,
                            age_40_60 = agea > 40 & agea <= 60,
                            age_60_70 = agea > 60 & agea <= 70,
                            age_gt_70 = agea >  70,
                            married = maritalb == 1,
                            edu1 = edubde1 == 2 | edubde1 == 3,
                            edu2 = edubde1 == 4,
                            edu3 = edubde1 == 5 | edubde1 == 6,
                            city = domicil == 1 | domicil == 2,
                            town = domicil == 3,
                            village = domicil == 4 | domicil == 5,
                            designgewicht = dweight,
                            gewicht = pspwght,
                            partei = case_when(prtvede2 == 1~"Union",
                                     prtvede2 == 2~"SPD",
                                     prtvede2 == 3~"Linke",
                                     prtvede2 == 4~"Grünen",
                                     prtvede2 == 5~"FDP",
                                     prtvede2 == 6~"AFD",
                                     prtvede2 == 7|prtvede2 == 8|prtvede2 == 9 ~"Sonstige"),
                            parteinw = case_when(prtvede2 == 1~"Union",
                                     prtvede2 == 2~"SPD",
                                     prtvede2 == 3~"Linke",
                                     prtvede2 == 4~"Grünen",
                                     prtvede2 == 5~"FDP",
                                     prtvede2 == 6~"AFD",
                                     prtvede2 == 7|prtvede2 == 8|prtvede2 == 9 ~"Sonstige",
                                     vote== 2 ~ "Nichtwähler"))
ESS9DE$partei <- factor(ESS9DE$partei, levels = c("Union","SPD","Linke","Grünen","FDP","AFD","Sonstige"))
ESS9DE$parteinw <- factor(ESS9DE$partei, levels = c("Union","SPD","Linke","Grünen","FDP","AFD","Sonstige","Nichtwähler"))
# table(ESS9DE$partei)


ESS9DE$partei <- as.factor(ESS9DE$partei)
ESS9DE$parteinw <- as.factor(ESS9DE$parteinw)
info <- ESS9DE %>%  select(idno, gewicht,designgewicht)
xVar <- ESS9DE %>%  select(age_le_20,age_20_40,age_40_60,age_60_70,age_gt_70,
                           male,edu1, edu2, edu3, married, city, town, village)

yvar <- ESS9DE %>%  select(partei) 
subs <- ESS9DE %>%  select(internet, blogger,interpol) 
xnam <- paste("male + age_le_20 + age_20_40 + age_60_70 + age_gt_70 +
                               edu1 + edu2  + married + city + town ")
xnam_partei <- paste("male + age_le_20 + age_20_40  + age_60_70 + age_gt_70  +
  edu1 + edu2  + married + city + town  + partei")

```


## Teildatensatz und MAR Annahme
```{r}

germany_18 <- cbind(yvar,subs,xVar,info)
germany_18 <- germany_18[complete.cases(germany_18[c(variable.names(xVar),variable.names(yvar))]),]
# germany_18$partei <- as.factor(germany_18$partei)
germany_18 <- germany_18[complete.cases(germany_18[variable.names(xVar)]),]

table(germany_18$internet,germany_18$partei,exclude = NULL)

germany_18[variable.names(cbind(xVar,subs))] <- ifelse (germany_18[variable.names(cbind(xVar,subs))]==T,1,0)


?glm

table(germany_18$internet)
germany_18$partei <- factor(germany_18$partei, levels = c("Linke","FDP","Grünen","SPD","Union","AFD","Sonstige"))

impact_internet = glm(as.formula(paste("internet ~ ", paste(xnam_partei))), weights = NULL , germany_18,
                      family=binomial())

impact_blogger= glm(as.formula(paste("blogger ~ ", paste(xnam_partei))) , weights = NULL , germany_18,
                    family=binomial())

impact_interpol = glm(as.formula(paste("interpol ~ ", paste(xnam_partei))), weights = NULL , germany_18,
                      family=binomial())

summary(impact_internet)#SAR
summary(impact_blogger)# SAR
summary(impact_interpol)# SAR


anov_inter <- anova(impact_internet,test= "Chisq")
anov_onl <- anova(impact_blogger,test= "Chisq")
anov_interpol <- anova(impact_interpol,test= "Chisq")
# anov_inter <- summary(aov(formula =impact_internet )) #SAR
# anov_onl   <- summary(aov(formula =impact_blogger )) #nicht SAR
# anov_interpol <- summary(aov(formula =impact_interpol )) #SAR


model_full_int = glm(as.formula(paste("internet ~ ", paste(xnam_partei))), weights = NULL , germany_18,
                      family=binomial())
model_reduced_int = glm(as.formula(paste("internet ~ ", paste(xnam))), weights = NULL , germany_18,
                      family=binomial())

model_full_onl = glm(as.formula(paste("blogger ~ ", paste(xnam_partei))), weights = NULL , germany_18,
                      family=binomial())
model_reduced_onl = glm(as.formula(paste("blogger ~ ", paste(xnam))), weights = NULL , germany_18,
                      family=binomial())

model_full_inpol = glm(as.formula(paste("interpol ~ ", paste(xnam_partei))), weights = NULL , germany_18,
                      family=binomial())
model_reduced_inpol = glm(as.formula(paste("interpol ~ ", paste(xnam))), weights = NULL , germany_18,
                      family=binomial())

# anova(model_reduced_int, model_full_int, test="LRT")
lrtest(model_full_int, model_reduced_int) #SAR
lrtest(model_full_onl, model_reduced_onl) # nicht SAR
lrtest(model_full_inpol, model_reduced_inpol) #SAR

?stargazer
# stargazer(impact_internet,impact_blogger,impact_interpol,
#           type="text", title = "Einfluss der Hilfsvariablen auf log odds am Online Panel teilzunehmen. ", decimal.mark = ",",
#           out = "Z:/Civey/Zwischenergebnisse_sonst/Wahlentscheidung/SAR- Annahme/SAR-Wahleintscheidung.html",
#           dep.var.labels = c("Internet","Blogger","Interpol"),
#           covariate.labels = c("Männlich (Ja)","Alter<20 vs.40-60","20-40 vs.40-60","60-70 vs.40-60","Alter>70 vs.40-60",
#                                "Bildung niedrig vs. hoch","Bildung mitte vs. hoch","Verheiratet (Ja)",
#                                "Großstadt vs. Dorf", "Stadt vs. Dorf",
#                                "Union vs. Nichtwähler",
#                                "SPD vs. Nichtwähler","Linke vs. Nichtwähler","Grüne vs. Nichtwähler",
#                                "FDP vs. Nichtwähler","AFD vs. Nichtwähler","Sonstige vs. Nichtwähler","(Intercept)" ))



germany_18$partei <- factor(germany_18$partei, levels = c("Union","SPD","Linke","Grünen","FDP","AFD","Sonstige"))

```
## Sample Vorbereitungen

```{r}
set.seed(090421)
Univ_18 <- sampling_wr(germany_18,100000,T)

# subset
subset_internet <- Univ_18 %>%  filter(internet == 1)
subset_blogger <- Univ_18 %>%  filter(blogger == 1)
subset_interpol  <- Univ_18 %>%  filter(interpol  == 1)

subset_internet <- Univ_18 %>%  filter(internet == 1)
subset_blogger <- Univ_18 %>%  filter(blogger == 1)
subset_interpol  <- Univ_18 %>%  filter(interpol  == 1)


psp <- design.table(Univ_18 ,~gewicht,~partei)
int <- design.table(subset_internet,~gewicht,~partei)
blog <- design.table(subset_blogger,~gewicht,~partei)
inpol <- design.table(subset_interpol,~gewicht,~partei)



# calibration -------------------------------------------------------------
margins <- rakemarg(Univ_18,xVar)

```
## Schleife
```{r}
#schleife
set.seed(090421)

r <- 10
c <- 2500
internet.cor <- matrix(0,nrow = r,ncol=dim(table(yvar)))
blogger.cor  <- matrix(0,nrow = r,ncol=dim(table(yvar)))
interpol.cor <- matrix(0,nrow = r,ncol=dim(table(yvar)))

internet.bias <- matrix(0,nrow = r,ncol=dim(table(yvar)))
blogger.bias  <- matrix(0,nrow = r,ncol=dim(table(yvar)))
interpol.bias <- matrix(0,nrow = r,ncol=dim(table(yvar)))

internet.relbias <- matrix(0,nrow = r,ncol=dim(table(yvar)))
blogger.relbias  <- matrix(0,nrow = r,ncol=dim(table(yvar)))
interpol.relbias <- matrix(0,nrow = r,ncol=dim(table(yvar)))

internet.se <- matrix(0,nrow = r,ncol=dim(table(yvar)))
blogger.se  <- matrix(0,nrow = r,ncol=dim(table(yvar)))
interpol.se <- matrix(0,nrow = r,ncol=dim(table(yvar)))



internet.rak <- matrix(0,nrow = r,ncol=dim(table(yvar)))
blogger.rak  <- matrix(0,nrow = r,ncol=dim(table(yvar)))
interpol.rak <- matrix(0,nrow = r,ncol=dim(table(yvar)))


internet.bias.rak <- matrix(0,nrow = r,ncol=dim(table(yvar)))
blogger.bias.rak  <- matrix(0,nrow = r,ncol=dim(table(yvar)))
interpol.bias.rak <- matrix(0,nrow = r,ncol=dim(table(yvar)))

internet.relbias.rak <- matrix(0,nrow = r,ncol=dim(table(yvar)))
blogger.relbias.rak  <- matrix(0,nrow = r,ncol=dim(table(yvar)))
interpol.relbias.rak <- matrix(0,nrow = r,ncol=dim(table(yvar)))

internet.se.rak <- matrix(0,nrow = r,ncol=dim(table(yvar)))
blogger.se.rak  <- matrix(0,nrow = r,ncol=dim(table(yvar)))
interpol.se.rak <- matrix(0,nrow = r,ncol=dim(table(yvar)))

pseudoweights_blogger  <- matrix(0,nrow = r,ncol = c)
pseudoweights_internet <- matrix(0,nrow = r,ncol = c)
pseudoweights_interpol <- matrix(0,nrow = r,ncol = c)

calibrationweights_blogger  <- matrix(0,nrow = r,ncol = c)
calibrationweights_internet <- matrix(0,nrow = r,ncol = c)
calibrationweights_interpol <- matrix(0,nrow = r,ncol = c)

start_time <- Sys.time()

for (i in 1:r) {
  #sample

  sample_internet <- sampling_wr(subset_internet, c,F)
  sample_blogger <-  sampling_wr(subset_blogger, c,F)
  sample_interpol <- sampling_wr(subset_interpol, c,F)

  pseudoweights_blogger[i,]  <- qrm(Univ_18,sample_blogger)
  pseudoweights_internet[i,] <- qrm(Univ_18,sample_internet)
  pseudoweights_interpol[i,] <- qrm(Univ_18,sample_interpol)
  
  # pseudoweights_blogger[i,] <- pseudoweights_blogger[i,]*c/sum(pseudoweights_blogger[i,])
  
  

  internet.cor[i,] <- design.table(sample_internet,pseudoweights_internet[i,],~partei)
  blogger.cor[i,] <- design.table(sample_blogger,pseudoweights_blogger[i,],~partei)
  interpol.cor[i,] <- design.table(sample_interpol,pseudoweights_interpol[i,],~partei)
  
  internet.bias[i,] <- abs.bias(internet.cor[i,],psp)
  blogger.bias[i,] <- abs.bias(blogger.cor[i,],psp)
  interpol.bias[i,] <- abs.bias(interpol.cor[i,],psp)
  
  internet.relbias[i,] <- rel.bias(internet.cor[i,],psp)
  blogger.relbias[i,] <- rel.bias(blogger.cor[i,],psp)
  interpol.relbias[i,] <- rel.bias(interpol.cor[i,],psp)
  
  internet.se[i,] <- se(internet.cor[i,],psp)
  blogger.se[i,] <- se(blogger.cor[i,],psp)
  interpol.se[i,] <- se(interpol.cor[i,],psp)
  
  
  ####raking
  
  sample_internet$gewicht_2 <- sample_internet$gewicht*100
  sample_blogger$gewicht_2 <- sample_blogger$gewicht*100
  sample_interpol$gewicht_2 <- sample_interpol$gewicht*100
  
  
  calibrationweights_internet[i,] <- calibration(sample_internet, marginMatrix=margins, colWeights="gewicht_2"
                               , method="raking", description=F,maxIter=2500)
  calibrationweights_blogger[i,] <- calibration(sample_blogger, marginMatrix=margins, colWeights="gewicht_2"
                              , method="raking", description=F,maxIter=2500)
  calibrationweights_interpol[i,] <- calibration(sample_interpol, marginMatrix=margins, colWeights="gewicht_2"
                               , method="raking", description=F,maxIter=2500)

internet.rak[i,] <- design.table(sample_internet,calibrationweights_internet[i,],~partei)
blogger.rak[i,] <- design.table(sample_blogger,calibrationweights_blogger[i,],~partei)
interpol.rak[i,] <- design.table(sample_interpol,calibrationweights_interpol[i,],~partei)
  

sum(pseudoweights_blogger[1,])

internet.bias.rak[i,]  <- abs.bias(internet.rak[i,],psp)
blogger.bias.rak[i,]   <- abs.bias(blogger.rak[i,],psp)
interpol.bias.rak[i,]  <- abs.bias(interpol.rak[i,],psp)
  
internet.relbias.rak[i,]  <- rel.bias(internet.rak[i,],psp)
blogger.relbias.rak[i,]   <- rel.bias(blogger.rak[i,],psp)
interpol.relbias.rak[i,]  <- rel.bias(interpol.rak[i,],psp) 

internet.se.rak[i,]  <- se(internet.rak[i,],psp)
blogger.se.rak[i,]   <- se(blogger.rak[i,],psp)
interpol.se.rak[i,]  <- se(interpol.rak[i,],psp) 


}
end_time <- Sys.time()
end_time-start_time


prop.table(table(sample_internet$partei))
```

## Analyse-Tools
```{r}
meaninternet.cor <- colMeans(internet.cor)
meaninternet.rak <- colMeans(internet.rak)
meanblogger.cor <- colMeans(blogger.cor)
meanblogger.rak <- colMeans(blogger.rak)
meaninterpol.cor <- colMeans(interpol.cor)
meaninterpol.rak <- colMeans(interpol.rak)

internet.abs.bias <- colSums(internet.bias)/r
blogger.abs.bias <- colSums(blogger.bias)/r
interpol.abs.bias <- colSums(interpol.bias)/r

internet.relativbias <- colSums(internet.relbias)/r
blogger.relativbias <- colSums(blogger.relbias)/r
interpol.relativbias <- colSums(interpol.relbias)/r

internet.rmse <- sqrt(colSums(internet.se)/r)
blogger.rmse <- sqrt(colSums(blogger.se)/r)
interpol.rmse <- sqrt(colSums(interpol.se)/r)



internet.abs.bias.rak <- colSums(internet.bias.rak)/r
blogger.abs.bias.rak <-colSums(blogger.bias.rak)/r
interpol.abs.bias.rak <-colSums(interpol.bias.rak)/r

internet.relativbias.rak <-colSums(internet.relbias.rak)/r
blogger.relativbias.rak <-colSums(blogger.relbias.rak)/r
interpol.relativbias.rak <-colSums(interpol.relbias.rak)/r

internet.rmse.rak <-sqrt(colSums(internet.se.rak)/r)
blogger.rmse.rak <-sqrt(colSums(blogger.se.rak)/r)
interpol.rmse.rak <-sqrt(colSums(interpol.se.rak)/r)


abs.bias_tabelle <- rbind(internet.abs.bias,internet.abs.bias.rak,
                          blogger.abs.bias,blogger.abs.bias.rak,
                          interpol.abs.bias,interpol.abs.bias.rak)

relativbias_tabelle <- rbind(internet.relativbias,internet.relativbias.rak,
                          blogger.relativbias,blogger.relativbias.rak,
                          interpol.relativbias,interpol.relativbias.rak)

rmse_tabelle <- rbind(internet.rmse,internet.rmse.rak,
                          blogger.rmse,blogger.rmse.rak,
                          interpol.rmse,interpol.rmse.rak)

internet_tabelle <- rbind(psp,int,meaninternet.cor,meaninternet.rak)
blogger_tabelle <- rbind(psp,blog,meanblogger.cor,meanblogger.rak)
interpol_tabelle <- rbind(psp,inpol,meaninterpol.cor,meaninterpol.rak)


# write.csv2(internet_tabelle, file = "Z:/Zwischenergebnisse_Nichtwahl/Wahlentscheidung/Tabellen/internet_tabelle.csv", quote = FALSE, row.names = T)
# write.csv2(blogger_tabelle, file = "Z:/Zwischenergebnisse_Nichtwahl/Wahlentscheidung/Tabellen/blogger_tabelle.csv", quote = FALSE, row.names = T)
# write.csv2(interpol_tabelle, file = "Z:/Zwischenergebnisse_Nichtwahl/Wahlentscheidung/Tabellen/interpol_tabelle.csv", quote = FALSE, row.names = T)


# write.csv2(abs.bias_tabelle, file = "Z:/Zwischenergebnisse_Nichtwahl/Wahlentscheidung/Tabellen/abs.bias_tabelle.csv", row.names = T, col.names = c("Union","SPD","Linke","Grünen","FDP","AFD","Sonstige","Nichtwähler"))
# write.csv2(relativbias_tabelle, file = "Z:/Zwischenergebnisse_Nichtwahl/Wahlentscheidung/Tabellen/relativbias_tabelle.csv", quote = FALSE, row.names = T)
# write.csv2(rmse_tabelle, file = "Z:/Zwischenergebnisse_Nichtwahl/Wahlentscheidung/Tabellen/rmse_tabelle.csv", quote = FALSE, row.names = T)

```



##Grafiken
```{r}


ESS <- design.table(ESS9DE ,~gewicht,~partei)

df2 <- data.frame(data=rep(c( "Wahl2017","ESS2018"), each=7),
                  part=rep(c("Union","SPD","Linke","Grünen","FDP","AFD","Sonstige"),2),
                  percent=(c(wahl,ESS)))
df2 $part = factor(df2$part, levels = c("Union","SPD","Linke","Grünen","FDP","AFD","Sonstige"))



ggplot(data=df2, aes(x=part, y=percent, fill=data)) +
  geom_bar(stat="identity", position=position_dodge())+
geom_text(aes(label=percent), vjust=1.6, color="white",
          position = position_dodge(0.9), size=3.5)+
  scale_fill_brewer(palette="Paired")+
  theme_minimal()





bias <- data.frame(rbind(cbind(internet.bias,rep("Internet",r)),
                         cbind(blogger.bias,rep("Blogger*",r)),
                         cbind(interpol.bias,rep("Interpol",r))))
names(bias) <- c("CDU","SPD","Linke","Grüne","FDP","AFD","Sonstige","Selektion")
bias[,1:length(table(yvar))] <- apply(bias[,1:length(table(yvar))], 2,as.numeric)

Internetabsbias <- c(abs.bias(int,psp),"Internet")
Bloggerabsbias <- c(abs.bias(blog,psp),"Blogger*")
Interpolabsbias <- c(abs.bias(inpol,psp),"Interpol")

verz <- as.data.frame(rbind(Internetabsbias,Bloggerabsbias,Interpolabsbias))
names(verz) <- c("CDU2","SPD2","Linke2","Grüne2","FDP2","AFD2","Sonstige2","Selektion2")
verz [,1:length(table(yvar))] <- apply(verz[,1:length(table(yvar))], 2,as.numeric)


plot1 <- plotter(bias,bias$Selektion,bias$CDU,verz,verz$Selektion2,verz$CDU2,"CDU")
plot2 <- plotter(bias,bias$Selektion,bias$SPD,verz,verz$Selektion2,verz$SPD2,"SPD")
plot3 <- plotter(bias,bias$Selektion,bias$Linke,verz,verz$Selektion2,verz$Linke2,"Linke")
plot4 <- plotter(bias,bias$Selektion,bias$Grüne,verz,verz$Selektion2,verz$Grüne2,"Grüne")
plot5 <- plotter(bias,bias$Selektion,bias$FDP,verz,verz$Selektion2,verz$FDP2,"FDP")
plot6 <- plotter(bias,bias$Selektion,bias$AFD,verz,verz$Selektion2,verz$AFD2,"AFD")
plot7 <- plotter(bias,bias$Selektion,bias$Sonstige,verz,verz$Selektion2,verz$Sonstige2,"Sonstige")

grid.arrange(plot1, plot2, plot3, plot4, plot5, plot6, plot7, nrow = 3, ncol = 3, top = textGrob("Pseudogewichtete Parteipräferenz",gp=gpar(fontsize=20,font=1)))

#raking

bias.rak <- data.frame(rbind(cbind(internet.bias.rak,rep("Internet",r)),
                         cbind(blogger.bias.rak,rep("Blogger*",r)),
                         cbind(interpol.bias.rak,rep("Interpol",r))))
names(bias.rak) <- c("CDU","SPD","Linke","Grüne","FDP","AFD","Sonstige","Selektion")
bias.rak[,1:length(table(yvar))] <- apply(bias.rak[,1:length(table(yvar))], 2,as.numeric)



plot1.rak <- plotter(bias.rak,bias.rak$Selektion,bias.rak$CDU,verz,verz$Selektion2,verz$CDU2,"CDU")
plot2.rak <- plotter(bias.rak,bias.rak$Selektion,bias.rak$SPD,verz,verz$Selektion2,verz$SPD2,"SPD")
plot3.rak <- plotter(bias.rak,bias.rak$Selektion,bias.rak$Linke,verz,verz$Selektion2,verz$Linke2,"Linke")
plot4.rak <- plotter(bias.rak,bias.rak$Selektion,bias.rak$Grüne,verz,verz$Selektion2,verz$Grüne2,"Grüne")
plot5.rak <- plotter(bias.rak,bias.rak$Selektion,bias.rak$FDP,verz,verz$Selektion2,verz$FDP2,"FDP")
plot6.rak <- plotter(bias.rak,bias.rak$Selektion,bias.rak$AFD,verz,verz$Selektion2,verz$AFD2,"AFD")
plot7.rak <- plotter(bias.rak,bias.rak$Selektion,bias.rak$Sonstige,verz,verz$Selektion2,verz$Sonstige2,"Sonstige")
grid.arrange(plot1.rak, plot2.rak, plot3.rak, plot4.rak, plot5.rak, plot6.rak, plot7.rak, nrow = 3, ncol = 3, top = textGrob("Calibrierte Parteipräferenz",gp=gpar(fontsize=20,font=1)))

```
